name: Blackshark Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Theos & SDK
        run: |
          sudo git clone --recursive https://github.com/theos/theos.git /var/theos
          git clone https://github.com/theos/sdks.git /tmp/sdks
          sudo mv /tmp/sdks/iPhoneOS14.5.sdk /var/theos/sdks/
          sudo chown -R $(id -u):$(id -g) /var/theos
          echo "THEOS=/var/theos" >> $GITHUB_ENV

      - name: Build
        run: |
          # Eğer JRMemory.framework ana dizindeyse sorun çıkmayacaktır
          make package FINALPACKAGE=1

      - name: Upload Artifact (V4)
        uses: actions/upload-artifact@v4
        with:
          name: Blackshark-Tweak
          path: packages/*.deb
