name: iOS UEDumper Build

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch: # Manuel tetikleme seçeneği

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install Theos
        run: |
          export THEOS=~/theos
          git clone --recursive https://github.com/theos/theos.git $THEOS
          echo "THEOS=$THEOS" >> $GITHUB_ENV
          echo "$THEOS/bin" >> $GITHUB_PATH

      - name: Install SDK
        run: |
          # Theos için gerekli iOS SDK'sını indirir (Genellikle 14.x veya 16.x tercih edilir)
          git clone https://github.com/theos/sdks.git $THEOS/sdks

      - name: Build Project
        run: |
          make clean
          make package FINALPACKAGE=1

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: iOS-UEDumper-Deb
          path: packages/*.deb
